import { useState } from "react";
import { Scanner } from "@yudiel/react-qr-scanner";
import { useSnackBarContext } from "@/context/SnackBarProvider";
import { ErrorFetching } from "../alerts";
import CameraSelectComponent from "@/components/qrcode/CameraSelectComponent";
import Typography from "@mui/material/TableContainer";
import Paper from "@mui/material/Paper";
import Box from "@mui/material/Box";
import TableContainer from "@mui/material/TableContainer";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableRow from "@mui/material/TableRow";


function QRCodeScanner() {
  // const [mode, setMode] = useState("Webcam");
  const [errorMessage, setErrorMessage] = useState(null);
  const [selectedDeviceId, setSelectedDeviceId] = useState("");
  const [data, setData] = useState({});
  const {
    openSnackbar,
    showSnackbar,
    hideSnackbar
  } = useSnackBarContext();

  const handleParsing = (res) => {
    if (openSnackbar) {
      hideSnackbar();
    }

    if (res && res[0].rawValue) {
      const parseData = JSON.parse(res[0].rawValue);

      setData(parseData);
    } else {
      console.error("Invalid qr code data.")
    }
  }

  const handleError = (error) => {
    const message = error.message;

    showSnackbar();
    setErrorMessage(message);
  } 

  return (
    <>
      <Box p={3}>
        <CameraSelectComponent
          selectedDeviceId={selectedDeviceId}
          setSelectedDeviceId={setSelectedDeviceId}
        />

        <Box
          display="flex"
          flexDirection={{ xs: "column", md: "row" }}
          gap={3}
          mt={3}
        >
          {/* Left: QR Scanner */}
          <Paper
            elevation={3}
            sx={{
              width: 400,
              height: 400,
              p: 2,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <Scanner
              onScan={handleParsing}
              onError={handleError}
              constraints={{ deviceId: selectedDeviceId }}
            />
          </Paper>

          {/* Right: Details Section */}
          <Paper
            elevation={3}
            sx={{
              flex: 1,
              p: 3,
              display: "flex",
              flexDirection: "column",
              gap: 2,
            }}
          >
            <Typography variant="h6">
              Scanned Details
            </Typography>

            {/* place th data here */}
            {
              data
                ? <QRCodeDetailAfterScan data={data} />
                : <Typography variant="body2" color="text.secondary">
                  Scan a QR code to display asset details.
                </Typography>
            }
            {/* <Typography variant="overline" color="text.secondary">
              You can input more information related to the scanned item here.
            </Typography> */}
          </Paper>
        </Box>

        {/* snackbar here */}
        {
          errorMessage && (
            <ErrorFetching 
              openSnackbar={openSnackbar}
              hideSnackbar={hideSnackbar}
              msg={errorMessage}
            />
          )
        }
      </Box>
    </>
  );
}

function QRCodeDetailAfterScan({ data }) {

  return (
    <TableContainer>
      <Table size="small">
        <TableBody>
          <TableRow>
            <TableCell>Asset ID</TableCell>
            <TableCell>{data.asset_id}</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Department</TableCell>
            <TableCell>{data.department}</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Item Name</TableCell>
            <TableCell>{data.item_name}</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Amount Purchased</TableCell>
            <TableCell>{data.amount_purchased}</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Brand</TableCell>
            <TableCell>{data.brand}</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Purchased Date</TableCell>
            <TableCell>{data.purchased_date}</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Location</TableCell>
            <TableCell>{data.location}</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Generated By</TableCell>
            <TableCell>
              {data.generated_by?.first_name} {data.generated_by?.last_name}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Updated By</TableCell>
            <TableCell>
              {data.updated_by?.first_name} {data.updated_by?.last_name}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </TableContainer>
  );
}

export default QRCodeScanner;