import TableBody from "@mui/material/TableBody";

import {
  TableHeadCreate,
  ShowNoRecordsFound,
  DepartmentPurchasedSummaryBody,
  AssetScanVerificationSummaryBody,
  LabelGenerationSummaryBody,
  DepreciationTableSummaryBody,
  MaintenanceReportSummaryBody
} from "@/components/TableHelpers";

const tableHeadForDptPurchasedSummary = [
  "Department", "Total Assets Purchased", "Total Expenditure", "Most Purchased Asset Type"
];

const tableHeadForAssetVerificationReport = [
  "Asset ID", "Item Name", "Expected Location",
  "Status", "Last Seen", "Generated By", "Updated By",
  "Value", "Days Missing"
];

const tableHeadForLabelGenerationReport = [
  "Asset ID", "Tag Type", "Generated By", "Timestamp", "Remarks"
]

const tableHeadForDepreciation = [
  "Asset ID", "Item Name", "Original Cost", "Asset Age Years", "Annual Depreciation",
  "Annual Depreciation PCT", "Depreciation Value", "Current Depreciation PCT",
  "Current Value", "Depreciation Method", "Useful Life"
]

const tableHeadForMaintenance = [
  "Info", "Asset ID", "Service Date", "Service Type", "Cost", "Status"
]

function TableSummary({ data, nameSummaryReport }) {
  const rows = data;

  if (nameSummaryReport === "dept-purchased-summary") {
    return (
      <>
        <TableHeadCreate
          tableCell={tableHeadForDptPurchasedSummary}
          keyName="dptPurchasedSummaryHeader"
          alignment="right"
        />

        <TableBody>
          {
            rows.length === 0
              ? <ShowNoRecordsFound />
              : <DepartmentPurchasedSummaryBody
                tableCell={data}
                keyName="dptPurchasedSumamryBody"
                alignment="right"
              />
          }
        </TableBody>
      </>
    );
  }
  else if (nameSummaryReport === "asset-scan-verification-report") {
    return (
      <>
        <TableHeadCreate
          tableCell={tableHeadForAssetVerificationReport}
          keyName="assetVerificationSummaryHeader"
          alignment="right"
        />

        <TableBody>
          {
            rows.length === 0
              ? <ShowNoRecordsFound colSpan={9} />
              : <AssetScanVerificationSummaryBody
                tableCell={data}
                keyName="assetScanVerificationSummaryBody"
                alignment="right"
              />
          }
        </TableBody>
      </>
    );
  }
  else if (nameSummaryReport === "label-generation-report") {
    return (
      <>
        <TableHeadCreate
          tableCell={tableHeadForLabelGenerationReport}
          keyName="labelGenerationSummaryHeader"
          alignment="right"
        />

        <TableBody>
          {
            rows.length === 0
              ? <ShowNoRecordsFound colSpan={5} />
              : <LabelGenerationSummaryBody
                tableCell={data}
                keyName="labelGenerationSummaryBody"
                alignment="right"
              />
          }
        </TableBody>
      </>
    );
  }
  else if (nameSummaryReport === "depreciation-report") {
    return (
      <>
        <TableHeadCreate
          tableCell={tableHeadForDepreciation}
          keyName="labelDepreciationSummaryHeader"
          alignment="right"
        />

        <TableBody>
          {
            rows.length === 0
              ? <ShowNoRecordsFound colSpan={11} />
              : <DepreciationTableSummaryBody
                tableCell={data}
                keyName="depreciateSummaryBody"
                alignment="right"
              />
          }
        </TableBody>
      </>
    );
  }
  else if (nameSummaryReport === "maintenance-report-summary") {
    return (
      <>
        <TableHeadCreate
          tableCell={tableHeadForMaintenance}
          keyName="labelMaintenanceSummaryHeader"
          alignment="right"
        />

        <TableBody>
          {
            rows.length === 0
              ? <ShowNoRecordsFound colSpan={6} />
              : <MaintenanceReportSummaryBody
                tableCell={data}
                keyName="maintenanceSummaryBody"
                alignment="right"
              />
          }
        </TableBody>
      </>
    )
  }

  return null;
}

export default TableSummary;
