"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
import os

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
# SECRET_KEY = "django-insecure-tgrx)i-gyxr53m3!sa(8+a4bqqu8w=27+!11u-ow3q%u0t4qfl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# SECURE TO TRUE IN PRODUCTION
SECURE_COOKIE = env("SECURE_COOKIE")

LOCAL_SERVER = env("LOCAL_SERVER")

ALLOWED_HOSTS = []

# local memory cached use redis for optimization.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",  # just a unique name for local memory cache
    }
}

### defined CONSTANTS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173"
]

CORS_ALLOW_CREDENTIALS = True

# MEDIA FILES HERE
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "application",
    "corsheaders",
    "django_filters",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

REST_FRAMEWORK = {
    # "DEFAULT_AUTHENTICATION_CLASSES": [
    #     "rest_framework_simplejwt.authentication.JWTAuthentication",
    # ],
    # "DEFAULT_FILTER_BACKENDS": [
    #     "django_filters.rest_framework.DjangoFilterBackend"
    # ]
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "application.api.CookiesJWTAuthentication.CookiesJWTAuthentication"
    ]
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    # "ROTATE_REFRESH_TOKENS": True
    # "BLACKLIST_AFTER_ROTATION": True
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# NOTE: defined this early
AUTH_USER_MODEL = 'application.Employee' # make this into default user model 

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DJANGO_ENV = env("DJANGO_ENV", default="development.MBPI")

if DJANGO_ENV == "development.MBPI":
    DATABASES = {
        "default": {
            'ENGINE': env("DB_ENGINE"),
            'NAME': env("DB_NAME"),
            'USER': env("DB_USER"),
            'PASSWORD': env("DB_PASSWORD"),
            'HOST': env("DB_HOST"),
            'PORT': env("DB_PORT")
        }
    }
elif DJANGO_ENV == "development.HOME":
    DATABASES = {
        "default": {
            'ENGINE': env("DB_ENGINE_LOCAL"),
            'NAME': env("DB_NAME_LOCAL"),
            'USER': env("DB_USER_LOCAL"),
            'PASSWORD': env("DB_PASSWORD_LOCAL"),
            'HOST': env("DB_HOST_LOCAL"),
            'PORT': env("DB_PORT_LOCAL")
        }
    }
elif DJANGO_ENV == "DOCKER":
    DATABASES = {
        "default": {
            'ENGINE': env("DB_ENGINE_DOCKER"),
            'NAME': env("DB_NAME_DOCKER"),
            'USER': env("DB_USER_DOCKER"),
            'PASSWORD': env("DB_PASSWORD_DOCKER"),
            'HOST': env("DB_HOST_DOCKER"),
            'PORT': env("DB_PORT_DOCKER")
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Manila"
USE_TZ = True  # Keep this True if you're storing in UTC but want to display in local time

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

