# Generated by Django 5.2 on 2025-05-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("department", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.IntegerField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=150, unique=True)),
                ("brand", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
