# Generated by Django 5.2 on 2025-05-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
