# Generated by Django 5.2 on 2025-05-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
