# Generated by Django 5.2 on 2025-05-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="qr_code_data",
            new_name="qr_code_base64",
        ),
    ]
