# Generated by Django 5.2 on 2025-05-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_rename_qr_code_data_asset_qr_code_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="qr_code_base64",
        ),
        migrations.AddField(
            model_name="asset",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr-codes/"),
        ),
    ]
