# Generated by Django 5.2 on 2025-05-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_asset_warranty_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("vendor_id", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_vente",
                to="application.vendor",
            ),
        ),
    ]
