# Generated by Django 5.2 on 2025-05-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_alter_department_department_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
