# Generated by Django 5.2 on 2025-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_vendor_asset_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
