# Generated by Django 5.2 on 2025-05-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_remove_asset_qr_code_base64_asset_qr_code_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
