# Generated by Django 5.2 on 2025-05-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_alter_item_item_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("asset_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_generated", models.DateField(auto_now_add=True)),
                (
                    "amount_purchased",
                    models.DecimalField(decimal_places=2, max_digits=19),
                ),
                ("qr_code_data", models.CharField()),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.department",
                    ),
                ),
                (
                    "item_name_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.item",
                    ),
                ),
            ],
        ),
    ]
