# Generated by Django 5.2 on 2025-05-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="date_generated",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="qr_code_data",
            field=models.CharField(max_length=300),
        ),
    ]
