# Generated by Django 5.2 on 2025-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_alter_vendor_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="vendor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
