# Generated by Django 5.2 on 2025-05-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_alter_asset_date_generated_alter_asset_qr_code_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="department_id",
            new_name="department_pii",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="item_name_id",
            new_name="item_name_pii",
        ),
    ]
