# Generated by Django 5.2 on 2025-05-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_alter_asset_vendor_delete_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicates whether the asset is active or retired.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="is_found",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Indicates whether the asset is found or missing.",
                null=True,
            ),
        ),
    ]
