# Generated by Django 5.2 on 2025-05-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_rename_department_id_asset_department_pii_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="amount_purchased",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=19, null=True
            ),
        ),
    ]
