# Generated by Django 5.2 on 2025-05-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0007_alter_asset_amount_purchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="qr_code_data",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
