# Generated by Django 5.2 on 2025-05-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0007_alter_asset_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="qr_code_date_generated",
        ),
    ]
