# Generated by Django 5.2 on 2025-05-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0008_remove_asset_qr_code_date_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_found",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
