# Generated by Django 5.2 on 2025-05-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0008_alter_asset_qr_code_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(max_length=150),
        ),
    ]
