# Generated by Django 5.2 on 2025-05-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0008_alter_assetmaintenance_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="assetmaintenance",
            table="application_asset_maintenance",
        ),
    ]
