# Generated by Django 5.2 on 2025-05-06 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0009_alter_item_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="department_pii",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_items",
                to="application.department",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="item_name_pii",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_items",
                to="application.item",
            ),
        ),
    ]
