# Generated by Django 5.2 on 2025-05-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0009_asset_is_found"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rel_location",
                to="application.location",
            ),
        ),
    ]
