# Generated by Django 5.2 on 2025-05-16 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0009_alter_assetmaintenance_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetmaintenance",
            name="id",
        ),
        migrations.AddField(
            model_name="assetmaintenance",
            name="maintenance_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="assetmaintenance",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_maintenance_record",
                to="application.asset",
            ),
        ),
    ]
