# Generated by Django 5.2 on 2025-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0010_alter_asset_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="tag_type",
            field=models.CharField(
                choices=[("QR", "QR Code"), ("RFID", "RFID Tag")],
                default="QR",
                max_length=10,
            ),
        ),
    ]
