# Generated by Django 5.2 on 2025-05-16 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0010_remove_assetmaintenance_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmaintenance",
            name="asset",
            field=models.ForeignKey(
                help_text="Select the asset that this maintenance record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_maintenance_record",
                to="application.asset",
            ),
        ),
        migrations.AlterField(
            model_name="assetmaintenance",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost of the maintenance service in your currency.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assetmaintenance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this maintenance record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="assetmaintenance",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee who performed the maintenance service (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assetmaintenance",
            name="remarks",
            field=models.CharField(
                blank=True,
                help_text="Additional notes or remarks about the maintenance.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assetmaintenance",
            name="service_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the maintenance service was performed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assetmaintenance",
            name="service_type",
            field=models.CharField(
                help_text="Type of maintenance service, e.g., Inspection, Repair, Upgrade.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="assetmaintenance",
            name="status",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicates if the maintenance was successful (True) or not (False).",
                null=True,
            ),
        ),
    ]
