# Generated by Django 5.2 on 2025-05-06 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0010_alter_asset_department_pii_alter_asset_item_name_pii"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
