# Generated by Django 5.2 on 2025-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0011_asset_created_at_asset_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="purchased_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
