# Generated by Django 5.2 on 2025-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0011_asset_tag_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="remarks",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
