# Generated by Django 5.2 on 2025-05-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0011_alter_assetmaintenance_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="rs_number",
            field=models.CharField(
                blank=True, help_text="Reference SNP ID, e.g., rs123456", null=True
            ),
        ),
    ]
