# Generated by Django 5.2 on 2025-05-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0012_asset_purchased_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="date_generated",
            new_name="qr_code_date_generated",
        ),
    ]
