# Generated by Django 5.2 on 2025-05-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0013_rename_date_generated_asset_qr_code_date_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
