# Generated by Django 5.2 on 2025-05-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0014_item_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_active",
        ),
        migrations.AddField(
            model_name="asset",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
