# Generated by Django 5.2 on 2025-05-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0015_remove_item_is_active_asset_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
