from rest_framework_simplejwt.views import TokenObtainPairView
from application.api.serializers import CustomTokenObtainPairSerializer

class CustomLoginTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer